#!/usr/bin/env bash

set -ueo pipefail

go fix ./... || exit 1
go vet ./... || exit 1
CGO_ENABLED=0 go build -o /dev/null . || exit 1
golangci-lint run ./... || exit

gitleaks git --verbose --config=./.gitleaks.toml
