version: "3"

tasks:
  compose:
    cmds:
      - docker compose up -d --build --remove-orphans
  decompose:
    cmds:
      - docker compose down --rmi local --remove-orphans --volumes
  recompose:
    cmds:
      - task: decompose
      - task: compose
  mcp:inspect:
    cmds:
      - docker run --rm -p 127.0.0.1:6274:6274 -p 127.0.0.1:6277:6277 -e HOST=0.0.0.0 -e MCP_AUTO_OPEN_ENABLED=false ghcr.io/modelcontextprotocol/inspector:latest
