version: "3"

dotenv:
  - .env

vars:
  AWS_REGION: il-central-1
  CLUSTER: il-news-bot
  SERVICE: il-news-bot

tasks:
  run:
    env:
      CGO_ENABLED: 0
    cmd: go run .
  build:
    env:
      CGO_ENABLED: 0
    cmd: go build -o main .
  watch:
    cmd: air
  tidy:
    cmd: go mod tidy

  cloud:ssh:
    vars:
      EC2_IP:
        sh: aws ec2 describe-instances --region il-central-1 --filters "Name=tag:aws:autoscaling:groupName,Values=il-news-bot-ec2-*" "Name=instance-state-name,Values=running" --query "Reservations[].Instances[].PublicIpAddress" --output text
    cmd: ssh -i ~/.ssh/keys/aws_ed25519 "ec2-user@{{.EC2_IP}}" "{{.COMMAND}}"
  cloud:logs:
    cmds:
      - vars:
          COMMAND: journalctl -xefu il-news-bot.service
        task: cloud:ssh

  deploy:
    env:
      TF_VAR_OPENROUTER_API_KEY: "{{.OPENROUTER_API_KEY}}"
      TF_VAR_TELEGRAM_BOT_TOKEN: "{{.TELEGRAM_BOT_TOKEN}}"
      TF_VAR_TELEGRAM_API_ID: "{{.TELEGRAM_API_ID}}"
      TF_VAR_TELEGRAM_API_HASH: "{{.TELEGRAM_API_HASH}}"
      TF_VAR_TELEGRAM_PHONE_NUMBER: "{{.TELEGRAM_PHONE_NUMBER}}"
      TF_VAR_ssh_allowed_ip:
        sh: curl -s https://checkip.amazonaws.com | tr -d "\n"
    cmd: tofu apply
  destroy:
    env:
      TF_VAR_OPENROUTER_API_KEY: "{{.OPENROUTER_API_KEY}}"
      TF_VAR_TELEGRAM_BOT_TOKEN: "{{.TELEGRAM_BOT_TOKEN}}"
      TF_VAR_TELEGRAM_API_ID: "{{.TELEGRAM_API_ID}}"
      TF_VAR_TELEGRAM_API_HASH: "{{.TELEGRAM_API_HASH}}"
      TF_VAR_TELEGRAM_PHONE_NUMBER: "{{.TELEGRAM_PHONE_NUMBER}}"
      TF_VAR_ssh_allowed_ip:
        sh: curl -s https://checkip.amazonaws.com | tr -d "\n"
    cmd: tofu destroy
